"""Add edited_date column to Note

Revision ID: eef51a2220a1
Revises: 49bed69a662e
Create Date: 2024-11-28 07:15:03.034795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef51a2220a1'
down_revision = '49bed69a662e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('edited_date')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
